---
- name: 'RedHat | Install locales'
  become: true
  block:
    - name: 'RedHat | Ensure the locales packages are installed'
      ansible.builtin.yum:
        name: '{{ __locales_packages }}'
        update_cache: true
        state: 'present'
      check_mode: false

    - name: 'RedHat | Ensure that locales are present'
      ansible.builtin.command: >-
        localedef
        -i "{{ locale_present.split('.')[0] }}"
        -f "{{ locale_present.split('.')[1] }}"
        '{{ locale_present }}'
      changed_when: false
      loop: '{{ locales_present_list }}'
      loop_control:
        loop_var: locale_present
      when: locales_present_list | length

    - name: 'RedHat | Ensure that locales are absent'
      ansible.builtin.command: >-
        localedef
        --delete-from-archive
         "{{ locale_absent.split('.')[0] }}.{{ locale_absent.split('.')[1] }}"
      changed_when: false
      loop: '{{ locales_absent_list }}'
      loop_control:
        loop_var: locale_absent
      when: locales_absent_list | length
