---
- name: 'Debian | Install locales'
  become: true
  block:
    - name: 'Debian | Ensure the locales package are installed'
      ansible.builtin.apt:
        name: 'locales'
        update_cache: true
        cache_valid_time: 3600
        state: 'present'
      check_mode: false

    - name: 'Debian | Ensure that locales are present'
      community.general.locale_gen:
        name: '{{ locale_present }}'
        state: 'present'
      loop: '{{ locales_present_list }}'
      loop_control:
        loop_var: locale_present
      when: locales_present_list | length

    - name: 'Debian | Ensure that locales are absent'
      community.general.locale_gen:
        name: '{{ locale_absent }}'
        state: 'absent'
      loop: '{{ locales_absent_list }}'
      loop_control:
        loop_var: locale_absent
      when: locales_absent_list | length

    - name: 'Configure locales'
      ansible.builtin.template:
        src: 'locale.j2'
        dest: '/etc/default/locale'
        owner: 'root'
        group: 'root'
        mode: 0644
